remote_theme           : "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
locale                 : "ko-KR"
search                 : true # true, false (default)
# Site Author
author:
  links:
# Site Footer
footer:
  links:
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "sidebar-category"   # ← 이 부분이 핵심!      
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "sidebar-category"